<?php
$data = array (
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'BURBERRY巴宝莉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '237',
    'name' => 'BURBERRY巴宝莉',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => 'BURBERRY巴宝莉',
    'measure_unit' => '',
    'parent_id' => '237',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => 'BURBERRY巴宝莉',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => 'BURBERRY皮带',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '241',
    'name' => 'BURBERRY皮带',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => 'BURBERRY女包',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '238',
    'name' => 'BURBERRY女包',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => 'BURBERRY服饰',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '242',
    'name' => 'BURBERRY服饰',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => 'BURBERRY男包',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '239',
    'name' => 'BURBERRY男包',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => 'BURBERRY太阳镜',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '243',
    'name' => 'BURBERRY太阳镜',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'BURBERRY鞋子',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '240',
    'name' => 'BURBERRY鞋子',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'BV宝缇嘉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '244',
    'name' => 'BV宝缇嘉',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => 'BV宝缇嘉',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '268',
    'name' => 'BV宝缇嘉',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => 'BV太阳镜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '250',
    'name' => 'BV太阳镜',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => 'BV钱包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => 'BV钱包',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'BV皮带',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '248',
    'name' => 'BV皮带',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'BV女包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '245',
    'name' => 'BV女包',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'BV鞋子',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => 'BV鞋子',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => 'BV男包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '246',
    'name' => 'BV男包',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => 'CARTIER卡地亚',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '261',
    'name' => 'CARTIER卡地亚',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => 'CARTIER卡地亚',
    'measure_unit' => '',
    'parent_id' => '261',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '275',
    'name' => 'CARTIER卡地亚',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => 'CARTIER太阳镜',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '264',
    'name' => 'CARTIER太阳镜',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => 'CARTIER腕表',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '262',
    'name' => 'CARTIER腕表',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => 'CARTIER皮带',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '263',
    'name' => 'CARTIER皮带',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '女神',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '277',
    'name' => '女神',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '耳钉',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '260',
    'name' => '耳钉',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'GUCCI古驰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '221',
    'name' => 'GUCCI古驰',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => 'GUCCI古驰',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => 'GUCCI古驰',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'GUCCI太阳镜',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '228',
    'name' => 'GUCCI太阳镜',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => 'GUCCI皮带',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '225',
    'name' => 'GUCCI皮带',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'GUCCI配饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => 'GUCCI配饰',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'GUCCI女包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '222',
    'name' => 'GUCCI女包',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'GUCCI鞋子',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '227',
    'name' => 'GUCCI鞋子',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'GUCCI男包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '223',
    'name' => 'GUCCI男包',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => 'PRADA普拉达',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '251',
    'name' => 'PRADA普拉达',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => 'PRADA普拉达',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '270',
    'name' => 'PRADA普拉达',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => 'PRADA男包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '253',
    'name' => 'PRADA男包',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => 'PRADA钱包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '254',
    'name' => 'PRADA钱包',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => 'PRADA鞋子',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '255',
    'name' => 'PRADA鞋子',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'PRADA女包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '252',
    'name' => 'PRADA女包',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'PRADA太阳镜',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '256',
    'name' => 'PRADA太阳镜',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'HERMES爱马仕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '229',
    'name' => 'HERMES爱马仕',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => 'HERMES爱马仕',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '276',
    'name' => 'HERMES爱马仕',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'HERMES皮带',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '234',
    'name' => 'HERMES皮带',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'HERMES男包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '231',
    'name' => 'HERMES男包',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => 'HERMES配饰',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '235',
    'name' => 'HERMES配饰',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => 'HERMES钱包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '232',
    'name' => 'HERMES钱包',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'HERMES腕表',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '236',
    'name' => 'HERMES腕表',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => 'HERMES鞋子',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '233',
    'name' => 'HERMES鞋子',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => 'HERMES女包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '230',
    'name' => 'HERMES女包',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => 'TODS托德斯',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '265',
    'name' => 'TODS托德斯',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => 'TODS托德斯',
    'measure_unit' => '',
    'parent_id' => '265',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '274',
    'name' => 'TODS托德斯',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => 'TODS太阳镜',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '267',
    'name' => 'TODS太阳镜',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => 'TODS鞋子',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '266',
    'name' => 'TODS鞋子',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => 'DIOR迪奥',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '257',
    'name' => 'DIOR迪奥',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => 'DIOR迪奥',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '269',
    'name' => 'DIOR迪奥',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'DIOR钱包',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '259',
    'name' => 'DIOR钱包',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'DIOR女包',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '258',
    'name' => 'DIOR女包',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'LV路易威登',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '212',
    'name' => 'LV路易威登',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => 'LV路易威登',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => 'LV路易威登',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'LV太阳镜',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '220',
    'name' => 'LV太阳镜',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'LV皮带',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '216',
    'name' => 'LV皮带',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'LV女包',
    'measure_unit' => '件',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '213',
    'name' => 'LV女包',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'LV鞋子',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '217',
    'name' => 'LV鞋子',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'LV男包',
    'measure_unit' => '件',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '214',
    'name' => 'LV男包',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => 'LV配饰',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => 'LV配饰',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => 'LV钱包',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '215',
    'name' => 'LV钱包',
  ),
);
?>