<?php
$data = array (
  0 => 
  array (
    'cat_id' => '261',
    'cat_name' => 'CARTIER卡地亚',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'GUCCI古驰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'BURBERRY巴宝莉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'BV宝缇嘉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '257',
    'cat_name' => 'DIOR迪奥',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '251',
    'cat_name' => 'PRADA普拉达',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'LV路易威登',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'HERMES爱马仕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '265',
    'cat_name' => 'TODS托德斯',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '271',
    'cat_name' => 'LV路易威登',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '272',
    'cat_name' => 'GUCCI古驰',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '276',
    'cat_name' => 'HERMES爱马仕',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '273',
    'cat_name' => 'BURBERRY巴宝莉',
    'measure_unit' => '',
    'parent_id' => '237',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '268',
    'cat_name' => 'BV宝缇嘉',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '270',
    'cat_name' => 'PRADA普拉达',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '269',
    'cat_name' => 'DIOR迪奥',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '275',
    'cat_name' => 'CARTIER卡地亚',
    'measure_unit' => '',
    'parent_id' => '261',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '274',
    'cat_name' => 'TODS托德斯',
    'measure_unit' => '',
    'parent_id' => '265',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '250',
    'cat_name' => 'BV太阳镜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '247',
    'cat_name' => 'BV钱包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'BV皮带',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'BV女包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'BV鞋子',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '246',
    'cat_name' => 'BV男包',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  24 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'DIOR钱包',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '260',
    'cat_name' => 'DIOR太阳镜',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'DIOR女包',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  27 => 
  array (
    'cat_id' => '253',
    'cat_name' => 'PRADA男包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '254',
    'cat_name' => 'PRADA钱包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'PRADA太阳镜',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '255',
    'cat_name' => 'PRADA鞋子',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  31 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'PRADA女包',
    'measure_unit' => '',
    'parent_id' => '270',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  32 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'LV鞋子',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  33 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'LV男包',
    'measure_unit' => '件',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  34 => 
  array (
    'cat_id' => '218',
    'cat_name' => 'LV配饰',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '215',
    'cat_name' => 'LV钱包',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  36 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'LV太阳镜',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'LV皮带',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  38 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'LV女包',
    'measure_unit' => '件',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  39 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'GUCCI鞋子',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  40 => 
  array (
    'cat_id' => '224',
    'cat_name' => 'GUCCI钱包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'GUCCI太阳镜',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '225',
    'cat_name' => 'GUCCI皮带',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'GUCCI女包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'GUCCI配饰',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'GUCCI男包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '243',
    'cat_name' => 'BURBERRY太阳镜',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'BURBERRY鞋子',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '241',
    'cat_name' => 'BURBERRY皮带',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '238',
    'cat_name' => 'BURBERRY女包',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '242',
    'cat_name' => 'BURBERRY服饰',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '239',
    'cat_name' => 'BURBERRY男包',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  52 => 
  array (
    'cat_id' => '266',
    'cat_name' => 'TODS鞋子',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '267',
    'cat_name' => 'TODS太阳镜',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  54 => 
  array (
    'cat_id' => '263',
    'cat_name' => 'CARTIER皮带',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '264',
    'cat_name' => 'CARTIER太阳镜',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  56 => 
  array (
    'cat_id' => '262',
    'cat_name' => 'CARTIER腕表',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'HERMES皮带',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'HERMES男包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '235',
    'cat_name' => 'HERMES配饰',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '232',
    'cat_name' => 'HERMES钱包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  61 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'HERMES腕表',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '233',
    'cat_name' => 'HERMES鞋子',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  63 => 
  array (
    'cat_id' => '230',
    'cat_name' => 'HERMES女包',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>